name: backend
on:
  pull_request: 
    branches:
      - "main"
    paths:
      - "backend/**"
  workflow_dispatch:
  workflow_run:
    workflows:
      - "frontend"
    types:
      - completed
      
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: this is backend test
        run: echo "helllo backend"
