name: frontend
on:
  pull_request: 
    branches:
      - "main"
    paths:
      - "frontend/**"
  workflow_dispatch:
    

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
      - name: this is frontend test
        run: echo "helllo frontend"
